FROM docker.io/debian:jessie

ENV DEBIAN_FRONTEND noninteractive

ENV LC_ALL en_US.UTF-8

RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/50no-install-recommends
RUN echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/50no-install-suggests

COPY project.tar /tmp

WORKDIR /var/www/

RUN tar -xvf /tmp/project.tar && chown -R root:root /var/www

RUN set -x \
 && apt-get update \
 && apt-get -y upgrade \
 && apt-get -y install \
    python3 \
    python3-chardet \
    python3-colorama \
    python3-html5lib \
    python3-pkg-resources \
    python3-requests \
    python3-six \
    python3-urllib3 \
    libgeos-c1 \
    libpq5 \
    libffi6 \
    make \
    python3-dev \
    python3-pip \
    libgeos-dev \
    libffi-dev \
    libpq-dev \
    virtualenv \
    gcc \
    git \
    locales \
 && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
 && locale-gen en_US.UTF-8 \
 && dpkg-reconfigure locales \
 && /usr/sbin/update-locale LANG=en_US.UTF-8 \
 && make -f config/dev install \
 && py3compile -f -X '^.*gevent/_util_py2.py$' -X '^.*attr/_next_gen.py$' .build/venv/ \
 && rm -fr .cache \
 && apt-get -y purge \
    python3-dev \
    python3-pip \
    libgeos-dev \
    libffi-dev \
    libpq-dev \
    virtualenv \
    gcc \
    git \
 && apt-get -y --purge autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV version="{version}" \
    PATH=/var/www/.build/venv/bin/:$PATH

COPY /docker-entrypoint.sh /
COPY /docker-entrypoint.d/* /docker-entrypoint.d/
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8080
CMD ["gunicorn", "--paste", "production.ini", "-u", "www-data", "-g", "www-data", "-b", ":8080"]

