[pytest]
addopts = --cov=c2corg_api
filterwarnings =
    default
    ignore::DeprecationWarning:pkg_resources
    ignore:pkg_resources is deprecated:DeprecationWarning
    ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning
    ignore:HTTPResponse.getheaders:DeprecationWarning:elasticsearch
