DOCUMENT_TYPE = 'd'
AREA_TYPE = 'a'
ARTICLE_TYPE = 'c'
IMAGE_TYPE = 'i'
MAP_TYPE = 'm'
OUTING_TYPE = 'o'
ROUTE_TYPE = 'r'
USERPROFILE_TYPE = 'u'
WAYPOINT_TYPE = 'w'
BOOK_TYPE = 'b'
XREPORT_TYPE = 'x'

ALL = [
    AREA_TYPE, ARTICLE_TYPE, IMAGE_TYPE, MAP_TYPE, OUTING_TYPE, ROUTE_TYPE,
    USERPROFILE_TYPE, WAYPOINT_TYPE, BOOK_TYPE, XREPORT_TYPE
]
