#!/bin/bash

set -e

# glibc sends A and AAAA queries in parallel from the same source port by
# default, which some environments' embedded DNS resolvers handle poorly
# (intermittently dropping one of the two responses). single-request-reopen
# makes it query sequentially with a fresh socket each time instead.
# /etc/resolv.conf is regenerated by Docker on every container start, so
# this has to happen here rather than at build time. It's also a bind
# mount: it must be rewritten via redirection (open+truncate in place),
# never with `sed -i` (which renames a temp file over the original and
# fails with "Device or resource busy" on a bind mount). Wrapped in
# `|| true` so this best-effort tweak can never block startup.
{
  if grep -q 'single-request-reopen' /etc/resolv.conf 2>/dev/null; then
    :
  elif grep -q '^options ' /etc/resolv.conf 2>/dev/null; then
    new="$(sed 's/^options .*/& single-request-reopen/' /etc/resolv.conf)"
    printf '%s\n' "$new" > /etc/resolv.conf
  else
    printf '%s\noptions single-request-reopen\n' "$(cat /etc/resolv.conf)" > /etc/resolv.conf
  fi
} || true

./scripts/env_replace config/env.default --keep-env .env < production.ini.in > production.ini
./scripts/env_replace config/env.default --keep-env .env < common.ini.in > common.ini

exec "$@"
