#!/bin/bash

set -e

# glibc sends A and AAAA queries in parallel from the same source port by
# default, which some environments' embedded DNS resolvers handle poorly
# (intermittently dropping one of the two responses). single-request-reopen
# makes it query sequentially with a fresh socket each time instead.
# /etc/resolv.conf is regenerated by Docker on every container start, so
# this has to happen here rather than at build time.
if grep -q 'single-request-reopen' /etc/resolv.conf 2>/dev/null; then
  :
elif grep -q '^options ' /etc/resolv.conf 2>/dev/null; then
  sed -i 's/^options .*/& single-request-reopen/' /etc/resolv.conf
else
  echo 'options single-request-reopen' >> /etc/resolv.conf
fi

./scripts/env_replace config/env.default --keep-env .env < production.ini.in > production.ini
./scripts/env_replace config/env.default --keep-env .env < common.ini.in > common.ini

exec "$@"
