FROM docker.io/python:3.9-slim-bullseye

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=en_US.UTF-8

RUN set -x \
    && apt-get update \
    && apt-get -y upgrade \
    && apt-get -y --no-install-recommends install locales \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && dpkg-reconfigure locales \
    && /usr/sbin/update-locale LANG=en_US.UTF-8

RUN set -x \
    && apt-get -y --no-install-recommends install \
    curl \
    jq \
    postgresql-client \
    git \
    libffi7 \
    libgeos-c1v5 \
    libpq5
RUN set -x \
 && apt-get -y purge \
 && apt-get -y --purge autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip

ENV version=''

WORKDIR /var/www/

COPY alembic_migration alembic_migration
COPY c2corg_api c2corg_api
COPY es_migration es_migration
COPY requirements.txt dev-requirements.txt MANIFEST.in *.ini setup.py README.md .
RUN pip install .

CMD ["pserve", "development.ini"]
