from sqlalchemy import Enum

from c2corg_api.models import Base, schema
from c2corg_api.models.common import attributes


def enum(name, types):
    return Enum(name=name, metadata=Base.metadata, schema=schema, *types)


quality_type = enum('quality_type', attributes.QualityTypes)
waypoint_type = enum('waypoint_type', attributes.WaypointTypes)
activity_type = enum('activity_type', attributes.Activities)
climbing_outdoor_type = enum('climbing_outdoor_type', attributes.ClimbingOutdoorTypes)
climbing_indoor_type = enum('climbing_indoor_type', attributes.ClimbingIndoorTypes)
public_transportation_type = enum(
    'public_transportation_type', attributes.PublicTransportationTypes
)
product_type = enum('product_type', attributes.ProductTypes)
ground_type = enum('ground_type', attributes.GroundTypes)
weather_station_type = enum('weather_station_type', attributes.WeatherStationTypes)
rain_proof_type = enum('rain_proof_type', attributes.RainProofTypes)
public_transportation_rating = enum(
    'public_transportation_rating', attributes.PublicTransportationRatings
)
paragliding_rating = enum('paragliding_rating', attributes.ParaglidingRatings)
children_proof_type = enum('children_proof_type', attributes.ChildrenProofTypes)
snow_clearance_rating = enum('snow_clearance_rating', attributes.SnowClearanceRatings)
exposition_rating = enum('exposition_rating', attributes.ExpositionRatings)
rock_type = enum('rock_type', attributes.RockTypes)
orientation_type = enum('orientation_type', attributes.OrientationTypes)
month_type = enum('month_type', attributes.Months)
parking_fee_type = enum('parking_fee_type', attributes.ParkingFeeTypes)
climbing_style = enum('climbing_style', attributes.ClimbingStyles)
access_time_type = enum('access_time_type', attributes.AccessTimes)
climbing_rating = enum('climbing_rating', attributes.ClimbingRatings)
equipment_rating = enum('equipment_rating', attributes.EquipmentRatings)
route_type = enum('route_type', attributes.RouteTypes)
route_duration_type = enum('route_duration_type', attributes.RouteDurationTypes)
glacier_gear_type = enum('glacier_gear_type', attributes.GlacierGearTypes)
route_configuration_type = enum(
    'route_configuration_type', attributes.RouteConfigurationTypes
)
ski_rating = enum('ski_rating', attributes.SkiRatings)
labande_ski_rating = enum('labande_ski_rating', attributes.LabandeSkiRatings)
global_rating = enum('global_rating', attributes.GlobalRatings)
engagement_rating = enum('engagement_rating', attributes.EngagementRatings)
risk_rating = enum('risk_rating', attributes.RiskRatings)
ice_rating = enum('ice_rating', attributes.IceRatings)
mixed_rating = enum('mixed_rating', attributes.MixedRatings)
exposition_rock_rating = enum(
    'exposition_rock_rating', attributes.ExpositionRockRatings
)
aid_rating = enum('aid_rating', attributes.AidRatings)
via_ferrata_rating = enum('via_ferrata_rating', attributes.ViaFerrataRatings)
hiking_rating = enum('hiking_rating', attributes.HikingRatings)
snowshoe_rating = enum('snowshoe_rating', attributes.SnowshoeRatings)
mtb_up_rating = enum('mtb_up_rating', attributes.MtbUpRatings)
mtb_down_rating = enum('mtb_down_rating', attributes.MtbDownRatings)
map_editor = enum('map_editor', attributes.MapEditors)
map_scale = enum('map_scale', attributes.MapScales)
area_type = enum('area_type', attributes.AreaTypes)
user_category = enum('user_category', attributes.UserCategories)
frequentation_type = enum('frequentation_type', attributes.FrequentationTypes)
access_condition = enum('access_condition', attributes.AccessConditions)
lift_status = enum('lift_status', attributes.LiftStatus)
condition_rating = enum('condition_rating', attributes.ConditionRatings)
glacier_rating = enum('glacier_rating', attributes.GlacierRatings)
avalanche_signs = enum('avalanche_signs', attributes.AvalancheSigns)
hut_status = enum('hut_status', attributes.HutStatus)
image_category = enum('image_category', attributes.ImageCategories)
image_type = enum('image_type', attributes.ImageTypes)
custodianship_type = enum('custodianship_type', attributes.CustodianshipTypes)
article_category = enum('article_category', attributes.ArticleCategories)
article_type = enum('article_type', attributes.ArticleTypes)
book_type = enum('book_type', attributes.BookTypes)
feed_change_type = enum('feed_change_type', attributes.FeedChangeTypes)
event_type = enum('event_type', attributes.EventTypes)
event_activity = enum('event_activity', attributes.EventActivities)
author_status = enum('author_status', attributes.AuthorStatuses)
activity_rate = enum('activity_rate', attributes.ActivityRates)
supervision = enum('supervision', attributes.Supervision)
qualification = enum('qualification', attributes.Qualification)
gender = enum('gender', attributes.Genders)
previous_injuries = enum('previous_injuries', attributes.PreviousInjuries)
severity = enum('severity', attributes.Severities)
autonomy = enum('autonomy', attributes.Autonomies)
avalanche_level = enum('avalanche_level', attributes.AvalancheLevels)
avalanche_slope = enum('avalanche_slope', attributes.AvalancheSlopes)
slackline_type = enum('slackline_type', attributes.SlacklineTypes)
lang = enum('lang', attributes.DefaultLangs)
snow_quality_ratings = enum('snow_quality_ratings', attributes.SnowQualityRatings)
snow_quantity_ratings = enum('snow_quantity_ratings', attributes.SnowQuantityRatings)
coverage_types = enum('coverage_types', attributes.CoverageTypes)
